FROM python:3.7-slim

COPY ./static/redoc.yaml ./static/

WORKDIR /app

COPY requirements.txt /app

RUN python -m pip install --upgrade pip

RUN pip3 install -r /app/requirements.txt --no-cache-dir

COPY ./ /app

CMD gunicorn api_yamdb.wsgi:application --bind 0:8000